# Generated by Django 3.2.4 on 2021-06-09 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_teacherstudent_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherstudent',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
