# Generated by Django 3.2.4 on 2021-06-09 12:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abilityVal', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionVal', ckeditor.fields.RichTextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('abilities', models.ManyToManyField(blank=True, related_name='option', to='questions.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionVal', ckeditor.fields.RichTextField()),
                ('options', models.ManyToManyField(blank=True, related_name='question', to='questions.Options')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionPaperTitle', models.CharField(default='', max_length=200)),
                ('questions', models.ManyToManyField(blank=True, related_name='test', to='questions.Question')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
        ),
    ]
